import "dotenv/config";
import pool from "./pool.js";

const ARTISTS = [
  { artist: "The Beatles", difficulty: "easy" },
  { artist: "Michael Jackson", difficulty: "easy" },
  { artist: "Elvis Presley", difficulty: "easy" },
  { artist: "Queen", difficulty: "easy" },
  { artist: "Madonna", difficulty: "easy" },
  { artist: "The Rolling Stones", difficulty: "medium" },
  { artist: "Pink Floyd", difficulty: "medium" },
  { artist: "Led Zeppelin", difficulty: "medium" },
  { artist: "Elton John", difficulty: "easy" },
  { artist: "Taylor Swift", difficulty: "easy" },
  { artist: "Eminem", difficulty: "easy" },
  { artist: "Rihanna", difficulty: "easy" },
  { artist: "Drake", difficulty: "easy" },
  { artist: "Beyoncé", difficulty: "easy" },
  { artist: "Stevie Wonder", difficulty: "medium" },
  { artist: "David Bowie", difficulty: "medium" },
  { artist: "Prince", difficulty: "medium" },
  { artist: "Bob Dylan", difficulty: "hard" },
  { artist: "The Weeknd", difficulty: "easy" },
  { artist: "Whitney Houston", difficulty: "easy" },
  { artist: "AC/DC", difficulty: "easy" },
  { artist: "Metallica", difficulty: "medium" },
  { artist: "Nirvana", difficulty: "easy" },
  { artist: "Kanye West", difficulty: "medium" },
  { artist: "Justin Bieber", difficulty: "easy" },
  { artist: "Adele", difficulty: "easy" },
  { artist: "Bruno Mars", difficulty: "easy" },
  { artist: "Ed Sheeran", difficulty: "easy" },
  { artist: "Lady Gaga", difficulty: "easy" },
  { artist: "Fleetwood Mac", difficulty: "medium" },
  { artist: "ABBA", difficulty: "easy" },
  { artist: "Guns N' Roses", difficulty: "easy" },
  { artist: "Bob Marley", difficulty: "easy" },
  { artist: "Aretha Franklin", difficulty: "medium" },
  { artist: "Bruce Springsteen", difficulty: "medium" },
  { artist: "U2", difficulty: "medium" },
  { artist: "Billy Joel", difficulty: "medium" },
  { artist: "Marvin Gaye", difficulty: "medium" },
  { artist: "Frank Sinatra", difficulty: "medium" },
  { artist: "Jay-Z", difficulty: "medium" },
  { artist: "Coldplay", difficulty: "easy" },
  { artist: "Linkin Park", difficulty: "easy" },
  { artist: "Billie Eilish", difficulty: "medium" },
  { artist: "Post Malone", difficulty: "medium" },
  { artist: "Ariana Grande", difficulty: "easy" },
  { artist: "Katy Perry", difficulty: "easy" },
  { artist: "Red Hot Chili Peppers", difficulty: "medium" },
  { artist: "The Doors", difficulty: "medium" },
  { artist: "Jimi Hendrix", difficulty: "hard" },
  { artist: "Johnny Cash", difficulty: "medium" },
  { artist: "Black Sabbath", difficulty: "medium" },
  { artist: "Bee Gees", difficulty: "easy" },
  { artist: "Britney Spears", difficulty: "easy" },
  { artist: "Mariah Carey", difficulty: "easy" },
  { artist: "Kendrick Lamar", difficulty: "medium" },
  { artist: "Harry Styles", difficulty: "medium" },
  { artist: "Dua Lipa", difficulty: "easy" },
  { artist: "Oasis", difficulty: "medium" },
  { artist: "Radiohead", difficulty: "hard" },
  { artist: "The Police", difficulty: "medium" },
  { artist: "Bon Jovi", difficulty: "easy" },
  { artist: "Phil Collins", difficulty: "medium" },
  { artist: "Genesis", difficulty: "hard" },
  { artist: "Green Day", difficulty: "easy" },
  { artist: "Foo Fighters", difficulty: "medium" },
  { artist: "Pearl Jam", difficulty: "medium" },
  { artist: "Aerosmith", difficulty: "medium" },
  { artist: "Depeche Mode", difficulty: "hard" },
  { artist: "The Cure", difficulty: "hard" },
  { artist: "Iron Maiden", difficulty: "hard" },
  { artist: "Snoop Dogg", difficulty: "easy" },
  { artist: "Notorious B.I.G.", difficulty: "medium" },
  { artist: "Tupac Shakur", difficulty: "medium" },
  { artist: "Amy Winehouse", difficulty: "medium" },
  { artist: "Lana Del Rey", difficulty: "medium" },
  { artist: "Arctic Monkeys", difficulty: "medium" },
  { artist: "The Killers", difficulty: "medium" },
  { artist: "Gorillaz", difficulty: "medium" },
  { artist: "Daft Punk", difficulty: "medium" },
  { artist: "Avicii", difficulty: "easy" },
  { artist: "Calvin Harris", difficulty: "easy" },
  { artist: "Shakira", difficulty: "easy" },
  { artist: "Selena Gomez", difficulty: "easy" },
  { artist: "Demi Lovato", difficulty: "medium" },
  { artist: "Joji", difficulty: "medium" },
  { artist: "One Direction", difficulty: "easy" },
  { artist: "Imagine Dragons", difficulty: "easy" },
  { artist: "Panic! At The Disco", difficulty: "medium" },
  { artist: "Fall Out Boy", difficulty: "medium" },
  { artist: "Twenty One Pilots", difficulty: "medium" },
  { artist: "Hozier", difficulty: "medium" },
  { artist: "SZA", difficulty: "medium" },
  { artist: "Tyler, The Creator", difficulty: "hard" },
  { artist: "Travis Scott", difficulty: "medium" },
  { artist: "Bad Bunny", difficulty: "medium" },
  { artist: "BTS", difficulty: "medium" },
  { artist: "Blackpink", difficulty: "medium" },
  { artist: "ONE OK ROCK", difficulty: "medium" },
  { artist: "Avril Lavigne", difficulty: "easy" },
  { artist: "Charlie Puth", difficulty: "medium" },
];

const seedSongs = async () => {
  for (const artist of ARTISTS) {
    const response = await fetch(
      `https://api.deezer.com/search?q=${encodeURIComponent(artist.artist)}`,
    );
    const data = await response.json();

    for (const song of data.data.slice(0, 5)) {
      await pool.query(
        `INSERT INTO songs (id, title, artist, preview_url, difficulty, deezer_id)
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT DO NOTHING`,
        [
          crypto.randomUUID(),
          song.title,
          artist.artist,
          song.preview,
          artist.difficulty,
          song.id,
        ],
      );
    }
    console.log(`Seeded ${artist.artist}`);
  }
  console.log("Done!");
  process.exit(0);
};

seedSongs();
